# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'crap' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for crap
  pod 'React', :path => '../node_modules/react-native', :subspecs =>
  [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTImage',
    'RCTVibration',
    'RCTWebSocket',
    'DevSupport'
  ]
  pod 'SQLCipher'
  # pod 'react-native-sqlcipher-storage', :path => '../node_modules/react-native-sqlcipher-storage'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'react-native-blur', :path => '../node_modules/react-native-blur'

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)',
          'SQLITE_HAS_CODEC',
          'SQLCIPHER',
          'SQLITE_TEMP_STORE=2',
        ]
      end
    end
  end
end
